config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  devise_scope :user do
    delete 'sign_out', to: 'devise/sessions#destroy'
  end
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, :likes
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/users/:id', to: 'users#show'
  get '/users/:user_id/posts', to: 'posts#index'
  get '/users/:user_id/posts/new', to: 'posts#new'
  get '/users/:user_id/posts/:id', to: 'posts#show'
  post '/users/:user_id/posts/new', to: 'posts#create'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_posts_counter

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  attribute :posts_counter, default: 0
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :email, :password, :bio) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :email, :password, :current_password, :bio)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @user.posts.find(params['post_id'])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to user_post_path(@user, @post) }
      else
        format.html { render :new }
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(like_params)
    @like.author = current_user
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) } if @like.save
    end
  end

  def like_params
    params.permit(:author_id, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :likes)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.author = current_user
    @post.comments_counter = 0
    @post.likes_counter = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path }
      else
        format.html { render :new }
      end
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <div class="form">
    <div class="form-field">
      <%= form.label :comment %> <br>
      <%= form.text_area :text, required: true %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= button_to 'Logout', destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNSbNt0" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<%= render('users/user_card', user: @user) %>
<%= link_to new_user_post_path() do %>
  <button>New Post</button>
<% end %>
<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post-and-comments">
      <%= link_to user_post_path(@user, post) do %>
        <div class="post">
          <h4>Post #<%= post.id %></h4>
          <h3>Title #<%= post.title %></h3>
          <p><%= post.text %></p>
          <small>Comments # <%= post.comments_counter %> and Likes # <%= post.likes_counter %></small>
        </div>
      <% end %>
      <% if post.comments.length.positive? %>
        <div class="comments">
            <% post.most_recent_comments.each do |comment| %>
              <p><%= comment.text.truncate(80, separator: ' ' ) %></p>
            <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
  <button>Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with model: @post, url: user_posts_path do |form| %>
  <div class="form">
    <div class="form-field">
      <%= form.label :title %> <br>
      <%= form.text_field :title, required: true %>
    </div>

    <div class="form-field">
      <%= form.label :post_text %> <br>
      <%= form.text_area :text, required: true %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="posts-container post-and-comments">
  <div class="full-post">
    <h4>Post #<%= @post.id %></h4>
    <h3>Title #<%= @post.title %> by <%= @user.name %></h3>
    <p class='post-counters'>Comments <%= @post.comments_counter %>, Likes <%= @post.likes_counter %></p>
    <p class='post-text'><%= @post.text %></p>
    <%= form_with model: Like.new, url: user_post_likes_path(@user, @post) do |form| %>
      <% form.submit :Like %>
    <% end %>
  </div>
  <%= link_to new_user_post_comment_path(@user, @post) do %>
  <button>New Comment</button>
  <% end %>
  <% if @post.comments.length.positive? %>
    <div class="comments">
        <% @post.comments.each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
    </div>
  <% end %>
</div>

app/views/users/_user_card.html.erb
<div class='user-card'>
  <img src=<%= user.photo %> alt=<%= user.name %>>
  <div>
    <h2><%= user.name %></h2>
    <p class='post-count' >Number of posts: <%= user.posts_counter %></p>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li> 
    <%= link_to(render('user_card', user: user), user_path(user)) %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render('user_card', user: @user) %>
<div class="user-info">
  <p><span>Bio: <br></span><%= @user.bio %></p>
  <% @user.recent_posts.each do |post|%>
    <%= link_to user_post_path(@user, post) do %>
      <div class="post">
        <h4>Post #<%= post.id %></h4>
        <p><%= post.text.truncate(100, separator: ' ') %></p>
      </div>
    <% end %>
  <% end %>
  <button><%= link_to('See all posts', user_posts_path(@user)) %></button>
</div>